field.storage_settings.rdf_file:
  type: field.storage_settings.file
  label: 'Rdf file settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.rdf_file:
  type: field.field_settings.file
  label: 'RDF file settings'

field.widget.settings.rdf_file_generic:
  type: field.widget.settings.file_generic
  label: 'RDF file generic widget'
